/* plantdb.js — built-in bilingual plant catalog: vegetables, herbs, berries,
 * fruit trees and ornamental trees/shrubs. The AI designs from this catalog
 * before inventing anything; care texts exist in EN and DE so the UI can show
 * them in the current language without translation. Species keys are lowercase
 * English and are used verbatim in plant "species"/"companions"/"avoid" fields.
 * Plain script. Exposes window.PlantDB.
 */
(function () {
  'use strict';

  /* Entry: [key, German name, habit, matureHeight, matureDiameter, spacing,
   *         companions, avoid, careEN[sun,water,soil,planting,harvest,notes], careDE[...]] */
  var DB = [
    // ---------- vegetables ----------
    ['tomato', 'Tomate', 'bushy', 1500, 500, 500, 'basil,onion,carrot,parsley', 'potato,fennel,cabbage',
      ['Full sun — at least 6–8 hours a day.',
       'Deep watering 2–3× per week at the base; keep the foliage dry.',
       'Rich, well-drained loam with plenty of compost, pH 6.0–6.8.',
       'Transplant after the last frost, 500 mm apart; bury the stem up to the first true leaves.',
       '60–85 days after transplanting; pick fully colored, harvest everything before the first frost.',
       'Stake or cage each plant. Pinch out side shoots weekly, feed every 2 weeks once fruiting.'],
      ['Volle Sonne — mindestens 6–8 Stunden täglich.',
       '2–3× pro Woche durchdringend an der Basis gießen; das Laub trocken halten.',
       'Nährstoffreicher, durchlässiger Lehmboden mit viel Kompost, pH 6,0–6,8.',
       'Nach den letzten Frösten pflanzen, Abstand 500 mm; den Stängel bis zu den ersten echten Blättern eingraben.',
       '60–85 Tage nach dem Auspflanzen; voll ausgefärbt pflücken, vor dem ersten Frost abernten.',
       'Jede Pflanze stützen. Wöchentlich ausgeizen, ab Fruchtansatz alle 2 Wochen düngen.']],
    ['cucumber', 'Gurke', 'climbing', 1800, 400, 400, 'beans,peas,dill,lettuce', 'tomato,potato,sage',
      ['Full sun, warm and sheltered.',
       'Plenty and regular — never let it dry out; use lukewarm water at the base.',
       'Humus-rich, warm soil with compost worked in.',
       'Plant out after the last frost, 400 mm apart, with a trellis to climb.',
       'Pick every 2–3 days once fruits reach size — frequent picking keeps it producing.',
       'Mulch keeps the shallow roots moist. Powdery mildew appears on drought-stressed plants.'],
      ['Volle Sonne, warm und geschützt.',
       'Reichlich und regelmäßig — nie austrocknen lassen; mit lauwarmem Wasser an der Basis gießen.',
       'Humusreicher, warmer Boden mit eingearbeitetem Kompost.',
       'Nach den letzten Frösten mit 400 mm Abstand pflanzen und ein Rankgitter geben.',
       'Alle 2–3 Tage ernten — häufiges Pflücken fördert den Ertrag.',
       'Mulch hält die flachen Wurzeln feucht. Mehltau tritt an trockengestressten Pflanzen auf.']],
    ['zucchini', 'Zucchini', 'bushy', 600, 900, 900, 'onion,beans,mint', 'potato,cucumber',
      ['Full sun.',
       'Generous watering at the base; the large leaves wilt quickly in heat.',
       'Very rich soil — a heavy feeder; plant on compost.',
       'One plant per m²; set out after the last frost, 900 mm apart.',
       'Cut fruits at 150–200 mm, 2–3× per week; oversized fruits stop production.',
       'Harvest young for the best flavor. One or two plants feed a family.'],
      ['Volle Sonne.',
       'Großzügig an der Basis gießen; die großen Blätter welken bei Hitze schnell.',
       'Sehr nährstoffreicher Boden — Starkzehrer; auf Kompost pflanzen.',
       'Eine Pflanze pro m²; nach den letzten Frösten mit 900 mm Abstand setzen.',
       'Früchte mit 150–200 mm schneiden, 2–3× pro Woche; übergroße Früchte stoppen den Ertrag.',
       'Jung geerntet schmecken sie am besten. Ein bis zwei Pflanzen versorgen eine Familie.']],
    ['pepper', 'Paprika', 'bushy', 800, 400, 400, 'basil,carrot,onion', 'fennel,beans',
      ['Full sun, warm and sheltered.',
       'Even moisture; never waterlogged.',
       'Rich, warm, well-drained soil.',
       'Plant out well after the last frost, 400 mm apart; peppers hate cold feet.',
       '60–90 days from transplanting; green peppers ripen to red/yellow with more sweetness.',
       'Support heavy plants with a small stake; feed every 2 weeks once flowering.'],
      ['Volle Sonne, warm und geschützt.',
       'Gleichmäßig feucht halten; keine Staunässe.',
       'Nährstoffreicher, warmer, durchlässiger Boden.',
       'Deutlich nach den letzten Frösten pflanzen, Abstand 400 mm; Paprika mag keine kalten Füße.',
       '60–90 Tage nach dem Pflanzen; grüne Früchte reifen zu rot/gelb mit mehr Süße.',
       'Schwere Pflanzen mit einem Stab stützen; ab der Blüte alle 2 Wochen düngen.']],
    ['chili', 'Chili', 'bushy', 700, 400, 400, 'basil,carrot', 'fennel,beans',
      ['Full sun — the more heat, the hotter the fruit.',
       'Moderate; slight drought stress increases pungency.',
       'Well-drained, moderately rich soil.',
       'Plant out after the last frost, 400 mm apart; pots work well.',
       'Pick when fully colored; regular picking triggers new flowers.',
       'Overwinter productive plants frost-free — chilis are perennial.'],
      ['Volle Sonne — je mehr Wärme, desto schärfer die Früchte.',
       'Mäßig gießen; leichter Trockenstress erhöht die Schärfe.',
       'Durchlässiger, mäßig nährstoffreicher Boden.',
       'Nach den letzten Frösten mit 400 mm Abstand pflanzen; auch gut im Topf.',
       'Voll ausgefärbt pflücken; regelmäßiges Ernten fördert neue Blüten.',
       'Produktive Pflanzen frostfrei überwintern — Chili ist mehrjährig.']],
    ['potato', 'Kartoffel', 'bushy', 600, 400, 350, 'beans,corn,cabbage', 'tomato,cucumber,pumpkin,onion',
      ['Full sun.',
       'Even moisture from flowering onward — that is when tubers form.',
       'Loose, deep soil; hill up soil around the stems twice.',
       'Plant seed potatoes 100 mm deep from mid-spring, 350 mm apart.',
       'New potatoes at flowering; storage crop when the foliage dies down.',
       'Never plant next to tomatoes (shared blight). Green tubers are toxic — keep covered.'],
      ['Volle Sonne.',
       'Ab der Blüte gleichmäßig feucht — dann bilden sich die Knollen.',
       'Lockerer, tiefgründiger Boden; zweimal anhäufeln.',
       'Pflanzkartoffeln ab Mitte Frühjahr 100 mm tief legen, Abstand 350 mm.',
       'Frühkartoffeln zur Blüte; Lagerware, wenn das Kraut abstirbt.',
       'Nie neben Tomaten (gemeinsame Krautfäule). Grüne Knollen sind giftig — bedeckt halten.']],
    ['carrot', 'Karotte', 'root', 250, 80, 75, 'tomato,onion,lettuce,leek', 'dill,parsnip',
      ['Full sun to light shade.',
       'Even moisture for straight roots; irregular watering makes them split.',
       'Deep, loose, sandy and stone-free. No fresh manure.',
       'Sow directly 5–10 mm deep from early spring; thin to 75 mm.',
       '70–80 days after sowing, when the shoulders are about 20 mm across.',
       'Onions or leeks nearby deter carrot fly; cover with netting until established.'],
      ['Volle Sonne bis lichter Schatten.',
       'Gleichmäßig feucht für gerade Wurzeln; unregelmäßiges Gießen lässt sie platzen.',
       'Tiefgründig, locker, sandig und steinfrei. Kein frischer Mist.',
       'Ab dem zeitigen Frühjahr 5–10 mm tief direkt säen; auf 75 mm vereinzeln.',
       '70–80 Tage nach der Aussaat, wenn die Schultern ca. 20 mm dick sind.',
       'Zwiebeln oder Lauch daneben vertreiben die Möhrenfliege; bis zum Anwachsen mit Netz abdecken.']],
    ['onion', 'Zwiebel', 'root', 300, 100, 100, 'carrot,lettuce,tomato,strawberry', 'beans,peas',
      ['Full sun.',
       'Moderate; stop watering 2 weeks before harvest so the bulbs cure.',
       'Firm, fertile, well-drained soil; not too much nitrogen.',
       'Push sets into the soil in early spring, tips just showing, 100 mm apart.',
       'When the tops yellow and fall over, lift and dry in the sun for a week.',
       'Its scent deters carrot fly and aphids — keep near carrots, away from legumes.'],
      ['Volle Sonne.',
       'Mäßig gießen; 2 Wochen vor der Ernte einstellen, damit die Zwiebeln ausreifen.',
       'Fester, nährstoffreicher, durchlässiger Boden; nicht zu viel Stickstoff.',
       'Steckzwiebeln im zeitigen Frühjahr stecken, Spitze knapp sichtbar, Abstand 100 mm.',
       'Wenn das Laub vergilbt und umknickt, ernten und eine Woche in der Sonne trocknen.',
       'Ihr Geruch vertreibt Möhrenfliege und Blattläuse — nah an Karotten, weg von Hülsenfrüchten.']],
    ['garlic', 'Knoblauch', 'root', 400, 80, 100, 'strawberry,tomato,carrot,rose', 'beans,peas',
      ['Full sun.',
       'Little water needed; keep dry in the last month before harvest.',
       'Loose, well-drained soil; bulbs rot in wet ground.',
       'Push cloves 50 mm deep in autumn (hardier) or early spring, 100 mm apart.',
       'When half the leaves have yellowed, lift and dry in an airy place.',
       'Natural fungicide of the bed — good beside strawberries and roses.'],
      ['Volle Sonne.',
       'Wenig Wasser; im letzten Monat vor der Ernte trocken halten.',
       'Lockerer, durchlässiger Boden; in nassem Boden faulen die Zehen.',
       'Zehen 50 mm tief im Herbst (robuster) oder zeitigen Frühjahr stecken, Abstand 100 mm.',
       'Wenn die Hälfte des Laubs vergilbt ist, ernten und luftig trocknen.',
       'Natürliches Fungizid im Beet — gut neben Erdbeeren und Rosen.']],
    ['leek', 'Lauch', 'root', 500, 100, 150, 'carrot,celery,lettuce', 'beans,peas',
      ['Full sun.',
       'Regular watering; drought makes the shafts tough.',
       'Deep, rich soil; hill up for long white shafts.',
       'Set seedlings in 150 mm deep holes, 150 mm apart, and water in without filling the hole.',
       'Autumn/winter as needed — leek stands in frost without spoiling.',
       'Deters carrot fly; rotate beds to avoid leek moth buildup.'],
      ['Volle Sonne.',
       'Regelmäßig gießen; Trockenheit macht die Schäfte zäh.',
       'Tiefgründiger, nährstoffreicher Boden; für lange weiße Schäfte anhäufeln.',
       'Setzlinge in 150 mm tiefe Löcher setzen, Abstand 150 mm, nur einschlämmen, nicht auffüllen.',
       'Herbst/Winter nach Bedarf — Lauch steht frosthart im Beet.',
       'Vertreibt die Möhrenfliege; Beet wechseln gegen Lauchmotten.']],
    ['lettuce', 'Salat', 'leafy', 200, 250, 250, 'carrot,onion,strawberry,radish', 'parsley,celery',
      ['Full sun in spring/autumn; light shade in high summer (it bolts in heat).',
       'Frequent light watering — shallow roots must stay moist.',
       'Loose, humus-rich soil, pH 6.0–7.0.',
       'Sow or transplant from early spring, 250 mm apart; re-sow every 2 weeks.',
       'Pick outer leaves as needed, or cut the whole head after 40–60 days.',
       'Slug-prone: check under the leaves in the evening. Taller neighbors give useful summer shade.'],
      ['Frühjahr/Herbst volle Sonne; im Hochsommer lichter Schatten (schießt bei Hitze).',
       'Häufig und leicht gießen — die flachen Wurzeln müssen feucht bleiben.',
       'Lockerer, humusreicher Boden, pH 6,0–7,0.',
       'Ab dem zeitigen Frühjahr säen oder pflanzen, Abstand 250 mm; alle 2 Wochen nachsäen.',
       'Äußere Blätter nach Bedarf pflücken oder den Kopf nach 40–60 Tagen schneiden.',
       'Schneckengefährdet: abends unter den Blättern kontrollieren. Höhere Nachbarn spenden Sommerschatten.']],
    ['spinach', 'Spinat', 'leafy', 250, 150, 150, 'strawberry,cabbage,radish', 'beet',
      ['Sun to half shade; a cool-season crop.',
       'Keep evenly moist — drought triggers bolting.',
       'Humus-rich soil with steady nitrogen.',
       'Sow directly in early spring or late summer, rows 250 mm apart.',
       'Cut leaves from 6 weeks; harvest before flower stalks appear.',
       'Its saponins benefit neighboring seedlings — a classic pre- and intercrop.'],
      ['Sonne bis Halbschatten; eine Kultur für die kühle Jahreszeit.',
       'Gleichmäßig feucht halten — Trockenheit lässt ihn schießen.',
       'Humusreicher Boden mit gleichmäßiger Stickstoffversorgung.',
       'Im zeitigen Frühjahr oder Spätsommer direkt säen, Reihen 250 mm.',
       'Blätter ab 6 Wochen schneiden; vor dem Blütenstand ernten.',
       'Seine Saponine fördern Nachbar-Sämlinge — klassische Vor- und Zwischenkultur.']],
    ['chard', 'Mangold', 'leafy', 450, 300, 300, 'cabbage,carrot,radish', 'beet,spinach',
      ['Sun to half shade.',
       'Regular watering keeps the stems tender.',
       'Deep, humus-rich soil.',
       'Sow from mid-spring, 300 mm apart; one sowing crops for months.',
       'Break outer stems continuously; the heart keeps producing.',
       'Much easier than spinach in summer — it does not bolt as readily.'],
      ['Sonne bis Halbschatten.',
       'Regelmäßiges Gießen hält die Stiele zart.',
       'Tiefgründiger, humusreicher Boden.',
       'Ab Mitte Frühjahr säen, Abstand 300 mm; eine Aussaat trägt monatelang.',
       'Äußere Stiele laufend brechen; das Herz treibt nach.',
       'Im Sommer deutlich unkomplizierter als Spinat — schießt kaum.']],
    ['kale', 'Grünkohl', 'leafy', 800, 500, 500, 'beet,celery,potato', 'strawberry,tomato',
      ['Full sun.',
       'Even moisture; mulch in summer.',
       'Rich, firm, lime-friendly soil.',
       'Set plants by midsummer, 500 mm apart, for an autumn/winter crop.',
       'Pick lower leaves after the first frosts — cold makes it sweeter.',
       'Net against cabbage white butterflies; very hardy, harvest all winter.'],
      ['Volle Sonne.',
       'Gleichmäßig feucht; im Sommer mulchen.',
       'Nährstoffreicher, fester, kalkfreundlicher Boden.',
       'Bis Hochsommer pflanzen, Abstand 500 mm, für die Herbst-/Winterernte.',
       'Untere Blätter nach den ersten Frösten pflücken — Kälte macht ihn süßer.',
       'Gegen Kohlweißlinge einnetzen; sehr winterhart, den ganzen Winter beerntbar.']],
    ['cabbage', 'Kohl', 'leafy', 400, 500, 500, 'potato,celery,dill,onion,beet', 'tomato,strawberry',
      ['Full sun.',
       'Steady, generous moisture for firm heads.',
       'Rich, firm, limed soil; a heavy feeder.',
       'Set seedlings deep, 500 mm apart; firm the soil well.',
       'Cut heads when firm; split heads follow heavy rain after drought.',
       'Rotate brassicas on a 3–4 year cycle against clubroot; net against cabbage whites.'],
      ['Volle Sonne.',
       'Gleichmäßig und reichlich gießen für feste Köpfe.',
       'Nährstoffreicher, fester, gekalkter Boden; Starkzehrer.',
       'Setzlinge tief pflanzen, Abstand 500 mm; Boden gut andrücken.',
       'Feste Köpfe schneiden; nach Regen auf Trockenheit platzen sie.',
       'Kohlarten nur alle 3–4 Jahre aufs selbe Beet (Kohlhernie); gegen Kohlweißlinge einnetzen.']],
    ['broccoli', 'Brokkoli', 'leafy', 600, 450, 450, 'celery,onion,potato,beet', 'tomato,strawberry',
      ['Full sun.',
       'Even moisture; stress makes it flower early.',
       'Rich, limed soil.',
       'Set out from mid-spring, 450 mm apart.',
       'Cut the main head before the buds open; side shoots follow for weeks.',
       'Harvest in the morning; keep cutting side shoots to extend the crop.'],
      ['Volle Sonne.',
       'Gleichmäßig feucht; Stress lässt ihn vorzeitig blühen.',
       'Nährstoffreicher, gekalkter Boden.',
       'Ab Mitte Frühjahr pflanzen, Abstand 450 mm.',
       'Die Hauptblume vor dem Öffnen der Knospen schneiden; Seitentriebe folgen wochenlang.',
       'Morgens ernten; Seitentriebe laufend schneiden verlängert die Ernte.']],
    ['cauliflower', 'Blumenkohl', 'leafy', 500, 500, 500, 'celery,beans,beet', 'tomato,strawberry',
      ['Full sun.',
       'Never let it dry out — the most moisture-sensitive brassica.',
       'Very rich, deep, limed soil.',
       'Set out from mid-spring, 500 mm apart.',
       'Cut while the curd is tight; break a leaf over it to keep it white.',
       'The diva among cabbages: any stress ruins the curd. Feed generously.'],
      ['Volle Sonne.',
       'Nie austrocknen lassen — der empfindlichste Kohl.',
       'Sehr nährstoffreicher, tiefgründiger, gekalkter Boden.',
       'Ab Mitte Frühjahr pflanzen, Abstand 500 mm.',
       'Schneiden, solange die Blume fest ist; ein geknicktes Blatt darüber hält sie weiß.',
       'Die Diva unter den Kohlarten: jeder Stress verdirbt die Blume. Großzügig düngen.']],
    ['radish', 'Radieschen', 'root', 150, 50, 50, 'lettuce,peas,carrot,spinach', '',
      ['Sun to half shade.',
       'Even, light moisture — drought makes them sharp and woody.',
       'Loose, humus-rich soil.',
       'Sow directly 10 mm deep from early spring, every 2 weeks; thin to 50 mm.',
       'Ready in 4–6 weeks; harvest promptly before they turn spongy.',
       'The fastest crop in the bed — ideal marker and intercrop between slow rows.'],
      ['Sonne bis Halbschatten.',
       'Gleichmäßig leicht feucht — Trockenheit macht sie scharf und holzig.',
       'Lockerer, humusreicher Boden.',
       'Ab dem zeitigen Frühjahr 10 mm tief direkt säen, alle 2 Wochen; auf 50 mm vereinzeln.',
       'Nach 4–6 Wochen erntereif; zügig ernten, bevor sie pelzig werden.',
       'Die schnellste Kultur im Beet — ideale Markier- und Zwischensaat.']],
    ['beet', 'Rote Bete', 'root', 300, 150, 150, 'onion,lettuce,cabbage,dill', 'spinach,chard',
      ['Full sun.',
       'Even moisture for tender roots.',
       'Deep, loose soil; tolerates salt, dislikes fresh manure.',
       'Sow directly from mid-spring, 50 mm apart, thin to 150 mm.',
       'Lift at tennis-ball size, 90–110 days; twist off the leaves.',
       'The young leaves are edible like chard. Store in damp sand.'],
      ['Volle Sonne.',
       'Gleichmäßig feucht für zarte Knollen.',
       'Tiefgründiger, lockerer Boden; verträgt Salz, keinen frischen Mist.',
       'Ab Mitte Frühjahr direkt säen, 50 mm Abstand, auf 150 mm vereinzeln.',
       'Bei Tennisballgröße ernten, 90–110 Tage; Laub abdrehen.',
       'Die jungen Blätter sind wie Mangold essbar. In feuchtem Sand lagern.']],
    ['peas', 'Erbsen', 'climbing', 1200, 200, 150, 'carrot,radish,cucumber,corn,lettuce', 'onion,garlic,leek',
      ['Full sun; a cool-season crop.',
       'Moderate until flowering, then steady moisture.',
       'Any decent garden soil — peas fix their own nitrogen.',
       'Sow directly 50 mm deep from early spring, 150 mm apart, with twiggy supports or netting.',
       'Pick pods every 2 days once filled; frequent picking prolongs flowering.',
       'Leave the roots in the ground after harvest — they feed the next crop with nitrogen.'],
      ['Volle Sonne; eine Kultur für die kühle Jahreszeit.',
       'Bis zur Blüte mäßig, danach gleichmäßig feucht.',
       'Jeder gute Gartenboden — Erbsen binden ihren Stickstoff selbst.',
       'Ab dem zeitigen Frühjahr 50 mm tief direkt säen, Abstand 150 mm, mit Reisig oder Netz als Stütze.',
       'Gefüllte Hülsen alle 2 Tage pflücken; häufiges Ernten verlängert die Blüte.',
       'Wurzeln nach der Ernte im Boden lassen — sie düngen die Folgekultur mit Stickstoff.']],
    ['beans', 'Bohnen', 'climbing', 2000, 300, 300, 'potato,cucumber,corn,celery,strawberry', 'onion,garlic,leek,fennel',
      ['Full sun, sheltered from wind.',
       'Steady moisture from flowering; water the base.',
       'Warm, loose soil — beans fix their own nitrogen.',
       'Sow after the last frost, 30 mm deep, 6–8 seeds around each pole.',
       'Pick pods young and stringless every 2–3 days.',
       'Raw beans are toxic — always cook. Never plant next to onions or garlic.'],
      ['Volle Sonne, windgeschützt.',
       'Ab der Blüte gleichmäßig feucht; an der Basis gießen.',
       'Warmer, lockerer Boden — Bohnen binden ihren Stickstoff selbst.',
       'Nach den letzten Frösten 30 mm tief säen, 6–8 Korn um jede Stange.',
       'Hülsen jung und fadenlos alle 2–3 Tage pflücken.',
       'Rohe Bohnen sind giftig — immer kochen. Nie neben Zwiebeln oder Knoblauch.']],
    ['corn', 'Mais', 'grass', 2000, 400, 400, 'beans,peas,cucumber,pumpkin,potato', 'tomato',
      ['Full sun.',
       'Plenty of water at flowering and cob fill.',
       'Rich, warm soil; a heavy feeder.',
       'Sow after the last frost in BLOCKS (not single rows) for wind pollination, 400 mm apart.',
       'When the silks turn brown and kernels squirt milky juice, pick and eat the same day.',
       'The classic “three sisters” partner: corn as trellis, beans for nitrogen, pumpkin as ground cover.'],
      ['Volle Sonne.',
       'Zur Blüte und Kornfüllung reichlich wässern.',
       'Nährstoffreicher, warmer Boden; Starkzehrer.',
       'Nach den letzten Frösten im BLOCK säen (nicht in Einzelreihen) für die Windbestäubung, Abstand 400 mm.',
       'Wenn die Narbenfäden braun sind und Körner milchig spritzen, ernten und am selben Tag essen.',
       'Der klassische „Drei-Schwestern“-Partner: Mais als Rankhilfe, Bohnen für Stickstoff, Kürbis als Bodendecker.']],
    ['pumpkin', 'Kürbis', 'vining', 500, 2000, 1500, 'corn,beans', 'potato',
      ['Full sun.',
       'Generous, deep watering; the huge leaves pump water.',
       'Plant directly on the compost heap or very rich soil.',
       'Sow/plant after the last frost; one plant needs 1.5–2 m² of room.',
       'Harvest when the stem is corky and the skin resists a fingernail; before frost.',
       'Put a board under each fruit against rot; store cured fruits at 12–15 °C for months.'],
      ['Volle Sonne.',
       'Großzügig und durchdringend gießen; die riesigen Blätter pumpen Wasser.',
       'Direkt auf den Komposthaufen oder sehr fetten Boden pflanzen.',
       'Nach den letzten Frösten säen/pflanzen; eine Pflanze braucht 1,5–2 m² Platz.',
       'Ernten, wenn der Stiel verkorkt und die Schale dem Fingernagel widersteht; vor dem Frost.',
       'Ein Brett unter jede Frucht gegen Fäulnis; ausgereifte Früchte monatelang bei 12–15 °C lagerbar.']],
    ['eggplant', 'Aubergine', 'bushy', 800, 450, 500, 'beans,pepper,thyme', 'potato,tomato',
      ['Full sun, as warm as possible.',
       'Even moisture; mulch against evaporation.',
       'Rich, warm, well-drained soil.',
       'Plant out well after the last frost, 500 mm apart; a black mulch film helps.',
       'Cut fruits glossy and springy — dull skin means overripe and bitter.',
       'Limit to 5–6 fruits per plant for size; watch for Colorado beetle.'],
      ['Volle Sonne, so warm wie möglich.',
       'Gleichmäßig feucht; gegen Verdunstung mulchen.',
       'Nährstoffreicher, warmer, durchlässiger Boden.',
       'Deutlich nach den letzten Frösten pflanzen, Abstand 500 mm; schwarze Mulchfolie hilft.',
       'Früchte glänzend und elastisch schneiden — matte Haut heißt überreif und bitter.',
       'Auf 5–6 Früchte pro Pflanze begrenzen; auf Kartoffelkäfer achten.']],
    ['strawberry', 'Erdbeere', 'leafy', 250, 300, 300, 'onion,garlic,lettuce,spinach,beans', 'cabbage',
      ['Full sun for sweet fruit.',
       'Water at the base; wet fruit rots.',
       'Humus-rich, slightly acid soil; plant through mulch.',
       'Plant in late summer for a full crop the next year, 300 mm apart, crown at soil level.',
       'Pick fully red with the calyx, in the morning; ever-bearers fruit until frost.',
       'Straw under the fruit keeps them clean; renew plants every 3 years, remove runners.'],
      ['Volle Sonne für süße Früchte.',
       'An der Basis gießen; nasse Früchte faulen.',
       'Humusreicher, leicht saurer Boden; durch Mulch pflanzen.',
       'Im Spätsommer pflanzen für volle Ernte im Folgejahr, Abstand 300 mm, Herz ebenerdig.',
       'Vollrot mit Kelch pflücken, morgens; immertragende fruchten bis zum Frost.',
       'Stroh unter den Früchten hält sie sauber; alle 3 Jahre verjüngen, Ausläufer entfernen.']],

    // ---------- herbs ----------
    ['basil', 'Basilikum', 'herb', 350, 250, 250, 'tomato', 'rue,sage',
      ['Full sun; tolerates light afternoon shade.',
       'Keep evenly moist; water at the base in the morning.',
       'Moist, well-drained, compost-enriched soil.',
       'Plant out after all frost risk, 250 mm apart — very frost-sensitive.',
       'Pinch whole shoot tips once 150 mm tall; regular picking keeps it bushy.',
       'Classic tomato companion: repels aphids and whitefly. Remove flower buds.'],
      ['Volle Sonne; verträgt leichten Halbschatten am Nachmittag.',
       'Gleichmäßig feucht halten; morgens an der Basis gießen.',
       'Feuchter, durchlässiger, kompostreicher Boden.',
       'Erst nach den Eisheiligen auspflanzen, Abstand 250 mm — sehr frostempfindlich.',
       'Ganze Triebspitzen ab 150 mm Höhe abknipsen; regelmäßiges Ernten hält ihn buschig.',
       'Klassischer Tomatenpartner: vertreibt Blattläuse und Weiße Fliege. Blütenknospen entfernen.']],
    ['parsley', 'Petersilie', 'herb', 300, 200, 200, 'tomato,onion,radish', 'lettuce,mint',
      ['Sun to half shade.',
       'Evenly moist; never waterlogged.',
       'Deep, humus-rich soil.',
       'Sow in place from early spring — germination takes 3–4 weeks; do not move it.',
       'Cut outer stalks continuously from the outside in.',
       'Biennial: it flowers in year two, then re-sow. Bad neighbor to lettuce.'],
      ['Sonne bis Halbschatten.',
       'Gleichmäßig feucht; keine Staunässe.',
       'Tiefgründiger, humusreicher Boden.',
       'Ab dem zeitigen Frühjahr an Ort und Stelle säen — Keimung dauert 3–4 Wochen; nicht verpflanzen.',
       'Äußere Stiele laufend von außen nach innen schneiden.',
       'Zweijährig: blüht im zweiten Jahr, dann neu säen. Schlechter Nachbar für Salat.']],
    ['chives', 'Schnittlauch', 'herb', 300, 150, 150, 'carrot,tomato,strawberry', 'beans,peas',
      ['Sun to half shade.',
       'Keep moist; it sulks in drought.',
       'Any humus-rich garden soil.',
       'Sow or divide clumps in spring, 150 mm apart; also thrives in pots.',
       'Cut whole bundles 20 mm above ground — cutting keeps them fine.',
       'The purple flowers are edible and loved by bees; divide every 3 years.'],
      ['Sonne bis Halbschatten.',
       'Feucht halten; bei Trockenheit stellt er das Wachstum ein.',
       'Jeder humusreiche Gartenboden.',
       'Im Frühjahr säen oder Horste teilen, Abstand 150 mm; gedeiht auch im Topf.',
       'Ganze Büschel 20 mm über dem Boden schneiden — Schnitt hält die Röhrchen fein.',
       'Die violetten Blüten sind essbar und bienenfreundlich; alle 3 Jahre teilen.']],
    ['dill', 'Dill', 'herb', 700, 250, 250, 'cucumber,cabbage,onion,beet', 'carrot,fennel',
      ['Full sun, sheltered.',
       'Moderate; established plants handle dry spells.',
       'Loose, warm soil.',
       'Sow directly in place from mid-spring — dill hates transplanting.',
       'Snip leaf tips continuously; the umbels flavor pickled cucumbers.',
       'Keep away from carrots (related pests); it self-sows willingly.'],
      ['Volle Sonne, geschützt.',
       'Mäßig; etablierte Pflanzen vertragen Trockenphasen.',
       'Lockerer, warmer Boden.',
       'Ab Mitte Frühjahr direkt an Ort und Stelle säen — Dill hasst Verpflanzen.',
       'Blattspitzen laufend schneiden; die Dolden würzen Gewürzgurken.',
       'Von Karotten fernhalten (verwandte Schädlinge); sät sich willig selbst aus.']],
    ['mint', 'Minze', 'herb', 500, 400, 400, 'cabbage,tomato', 'parsley',
      ['Half shade; tolerates sun with moist soil.',
       'Loves moisture — the thirstiest herb in the garden.',
       'Rich, moist soil.',
       'Plant ONLY with a root barrier or in a sunken pot — it overruns beds.',
       'Cut whole stems before flowering for the strongest aroma.',
       'Extremely invasive through runners; cut back hard twice a year.'],
      ['Halbschatten; mit feuchtem Boden auch Sonne.',
       'Liebt Feuchtigkeit — das durstigste Kraut im Garten.',
       'Nährstoffreicher, feuchter Boden.',
       'NUR mit Wurzelsperre oder im eingesenkten Topf pflanzen — sie überwuchert Beete.',
       'Ganze Stängel vor der Blüte schneiden für das stärkste Aroma.',
       'Extrem invasiv über Ausläufer; zweimal jährlich stark zurückschneiden.']],
    ['thyme', 'Thymian', 'herb', 250, 300, 300, 'cabbage,strawberry,eggplant', '',
      ['Full sun — the hotter and drier, the more aromatic.',
       'Very little; overwatering kills it.',
       'Poor, sandy, well-drained soil; add sand and lime.',
       'Plant in spring, 300 mm apart; ideal for bed edges and dry walls.',
       'Cut sprigs year-round; harvest before flowering for drying.',
       'Trim after flowering, never into old wood. Bee magnet.'],
      ['Volle Sonne — je heißer und trockener, desto aromatischer.',
       'Sehr wenig; zu viel Wasser tötet ihn.',
       'Magerer, sandiger, durchlässiger Boden; Sand und Kalk einarbeiten.',
       'Im Frühjahr pflanzen, Abstand 300 mm; ideal für Beetränder und Trockenmauern.',
       'Zweige ganzjährig schneiden; zum Trocknen vor der Blüte ernten.',
       'Nach der Blüte schneiden, nie ins alte Holz. Bienenmagnet.']],
    ['rosemary', 'Rosmarin', 'shrub', 1000, 600, 600, 'beans,cabbage,carrot,sage', '',
      ['Full sun, warm and sheltered.',
       'Sparse; drought-tolerant once established.',
       'Poor, well-drained, limy soil — waterlogging is fatal.',
       'Plant in spring; in cold regions grow in a pot and overwinter frost-free.',
       'Cut sprigs year-round.',
       'Prune lightly after flowering, never into bare wood. Protect from winter wet.'],
      ['Volle Sonne, warm und geschützt.',
       'Sparsam; eingewachsen trockenheitsverträglich.',
       'Magerer, durchlässiger, kalkhaltiger Boden — Staunässe ist tödlich.',
       'Im Frühjahr pflanzen; in kalten Lagen im Topf kultivieren und frostfrei überwintern.',
       'Zweige ganzjährig schneiden.',
       'Nach der Blüte leicht schneiden, nie ins kahle Holz. Vor Winternässe schützen.']],
    ['sage', 'Salbei', 'shrub', 600, 500, 500, 'cabbage,carrot,strawberry,rosemary', 'cucumber,basil',
      ['Full sun.',
       'Little; established plants are drought-proof.',
       'Poor, limy, well-drained soil.',
       'Plant in spring, 500 mm apart.',
       'Pick leaves before flowering for the best aroma.',
       'Cut back by a third in spring to keep it compact; deters cabbage whites.'],
      ['Volle Sonne.',
       'Wenig; etablierte Pflanzen sind trockenfest.',
       'Magerer, kalkhaltiger, durchlässiger Boden.',
       'Im Frühjahr pflanzen, Abstand 500 mm.',
       'Blätter vor der Blüte pflücken für das beste Aroma.',
       'Im Frühjahr um ein Drittel zurückschneiden; vertreibt Kohlweißlinge.']],
    ['oregano', 'Oregano', 'herb', 400, 300, 300, 'cabbage,cucumber', '',
      ['Full sun.',
       'Little water; aroma grows with drought.',
       'Poor, limy, well-drained soil.',
       'Plant in spring, 300 mm apart.',
       'Cut whole stems at flowering — that is peak aroma; dries excellently.',
       'Hardy perennial; cut back in spring. Flowers feed bees and hoverflies.'],
      ['Volle Sonne.',
       'Wenig gießen; das Aroma wächst mit der Trockenheit.',
       'Magerer, kalkhaltiger, durchlässiger Boden.',
       'Im Frühjahr pflanzen, Abstand 300 mm.',
       'Ganze Stängel zur Blüte schneiden — dann ist das Aroma am stärksten; trocknet hervorragend.',
       'Winterharte Staude; im Frühjahr zurückschneiden. Blüten nähren Bienen und Schwebfliegen.']],
    ['lavender', 'Lavendel', 'shrub', 600, 500, 500, 'rose,cabbage,thyme', '',
      ['Full sun — a Mediterranean plant.',
       'Very little; never waterlogged.',
       'Poor, sandy, limy soil.',
       'Plant in spring, 500 mm apart; classic beside roses and paths.',
       'Cut flower stems just as the buds open, for drying.',
       'Prune by a third after flowering, never into old wood. Repels aphids near roses.'],
      ['Volle Sonne — eine Mittelmeerpflanze.',
       'Sehr wenig; nie Staunässe.',
       'Magerer, sandiger, kalkhaltiger Boden.',
       'Im Frühjahr pflanzen, Abstand 500 mm; klassisch neben Rosen und Wegen.',
       'Blütenstiele beim Öffnen der Knospen zum Trocknen schneiden.',
       'Nach der Blüte um ein Drittel schneiden, nie ins alte Holz. Vertreibt Blattläuse bei Rosen.']],

    // ---------- berries ----------
    ['raspberry', 'Himbeere', 'shrub', 1600, 500, 500, 'garlic', 'potato',
      ['Sun to light half shade.',
       'Even moisture; shallow roots — mulch thickly.',
       'Loose, humus-rich, slightly acid soil.',
       'Plant in autumn along a wire trellis, 500 mm apart.',
       'Summer raspberries fruit on last year’s canes, autumn ones on new canes.',
       'Cut fruited canes to the ground; autumn varieties are mowed entirely each winter.'],
      ['Sonne bis lichter Halbschatten.',
       'Gleichmäßig feucht; Flachwurzler — dick mulchen.',
       'Lockerer, humusreicher, leicht saurer Boden.',
       'Im Herbst an einem Drahtspalier pflanzen, Abstand 500 mm.',
       'Sommerhimbeeren tragen an vorjährigen Ruten, Herbstsorten an neuen.',
       'Abgetragene Ruten bodennah schneiden; Herbstsorten im Winter komplett mähen.']],
    ['blueberry', 'Heidelbeere', 'shrub', 1200, 1000, 1000, '', '',
      ['Sun to half shade.',
       'Keep moist with rainwater — tap water is too limy.',
       'STRICTLY acid soil, pH 4–5: plant in rhododendron/bog soil.',
       'Plant two varieties for cross-pollination, 1 m apart, in a peat-based pit.',
       'Pick berries a few days after they turn blue — then they are sweet.',
       'Mulch with bark or sawdust; net against birds. No lime, no regular compost.'],
      ['Sonne bis Halbschatten.',
       'Mit Regenwasser feucht halten — Leitungswasser ist zu kalkhaltig.',
       'STRENG saurer Boden, pH 4–5: in Rhododendron-/Moorbeeterde pflanzen.',
       'Zwei Sorten zur Befruchtung pflanzen, Abstand 1 m, in eine Torfgrube.',
       'Beeren einige Tage nach dem Blauwerden pflücken — dann sind sie süß.',
       'Mit Rinde oder Sägespänen mulchen; gegen Vögel einnetzen. Kein Kalk, kein normaler Kompost.']],
    ['currant', 'Johannisbeere', 'shrub', 1500, 1200, 1500, '', '',
      ['Sun to half shade; red tolerates more shade than black.',
       'Even moisture; mulch the shallow roots.',
       'Deep, humus-rich soil.',
       'Plant in autumn, slightly deeper than in the nursery pot, 1.5 m apart.',
       'Pick whole strigs when fully colored.',
       'Keep 8–10 main shoots; remove the oldest 2–3 at the base each winter.'],
      ['Sonne bis Halbschatten; Rote verträgt mehr Schatten als Schwarze.',
       'Gleichmäßig feucht; die flachen Wurzeln mulchen.',
       'Tiefgründiger, humusreicher Boden.',
       'Im Herbst etwas tiefer als im Topf pflanzen, Abstand 1,5 m.',
       'Ganze Trauben voll ausgefärbt pflücken.',
       '8–10 Haupttriebe halten; jeden Winter die 2–3 ältesten bodennah entfernen.']],
    ['gooseberry', 'Stachelbeere', 'shrub', 1200, 1000, 1500, '', '',
      ['Half shade — full sun scorches the fruit.',
       'Even moisture.',
       'Humus-rich, cool soil.',
       'Plant in autumn, 1.5 m apart; thorny — leave working room.',
       'Green (tart, for cooking) from early summer; fully ripe for eating fresh.',
       'Thin the bush yearly for airflow against mildew; mildew-resistant varieties exist.'],
      ['Halbschatten — volle Sonne verbrennt die Früchte.',
       'Gleichmäßig feucht.',
       'Humusreicher, kühler Boden.',
       'Im Herbst pflanzen, Abstand 1,5 m; stachelig — Arbeitsraum lassen.',
       'Grün (sauer, zum Kochen) ab Frühsommer; vollreif zum Frischessen.',
       'Jährlich auslichten für Luft gegen Mehltau; es gibt mehltaufeste Sorten.']],
    ['grape', 'Weinrebe', 'climbing', 3000, 1000, 1500, '', '',
      ['Full sun — a south-facing wall is ideal.',
       'Sparse once established; deep roots.',
       'Warm, stony, well-drained soil.',
       'Plant in spring against a wall or pergola with sturdy wires.',
       'Harvest when seeds are brown and berries aromatic, usually early–mid autumn.',
       'Prune hard in late winter (fruit forms on new wood); thin leaves around clusters.'],
      ['Volle Sonne — eine Südwand ist ideal.',
       'Eingewachsen sparsam gießen; tiefe Wurzeln.',
       'Warmer, steiniger, durchlässiger Boden.',
       'Im Frühjahr an Wand oder Pergola mit stabilen Drähten pflanzen.',
       'Ernten, wenn die Kerne braun und die Beeren aromatisch sind, meist Früh- bis Mittherbst.',
       'Im Spätwinter stark schneiden (Frucht am Neuholz); Blätter um die Trauben auslichten.']],

    // ---------- fruit trees ----------
    ['apple', 'Apfelbaum', 'tree', 3500, 3000, 3500, 'chives,garlic,lavender', 'walnut',
      ['Full sun.',
       'Water young trees weekly in dry spells; mulch the root zone.',
       'Deep, loamy, well-drained soil.',
       'Plant bare-root in autumn; needs a pollination partner flowering at the same time.',
       'From late summer depending on variety; ripe when the stalk parts with a light twist.',
       'Winter-prune for an airy crown; thin fruit clusters to singles in early summer. Chives at the base help against scab.'],
      ['Volle Sonne.',
       'Junge Bäume in Trockenphasen wöchentlich wässern; Baumscheibe mulchen.',
       'Tiefgründiger, lehmiger, durchlässiger Boden.',
       'Wurzelnackt im Herbst pflanzen; braucht einen gleichzeitig blühenden Befruchtungspartner.',
       'Je nach Sorte ab Spätsommer; reif, wenn sich der Stiel mit leichter Drehung löst.',
       'Winterschnitt für eine luftige Krone; Fruchtbüschel im Frühsommer auf Einzelfrüchte ausdünnen. Schnittlauch am Stamm hilft gegen Schorf.']],
    ['pear', 'Birnbaum', 'tree', 4000, 3000, 4000, 'garlic,chives', 'walnut',
      ['Full sun, warm — pears need more warmth than apples.',
       'Young trees regularly; established trees only in drought.',
       'Deep, warm, nutrient-rich soil.',
       'Plant in autumn; needs a pollination partner.',
       'Pick slightly firm and ripen indoors — tree-ripe pears turn mealy.',
       'Keep away from juniper (pear rust host). Espalier forms suit warm walls.'],
      ['Volle Sonne, warm — Birnen brauchen mehr Wärme als Äpfel.',
       'Junge Bäume regelmäßig; etablierte nur bei Trockenheit.',
       'Tiefgründiger, warmer, nährstoffreicher Boden.',
       'Im Herbst pflanzen; braucht einen Befruchtungspartner.',
       'Leicht fest pflücken und im Haus nachreifen lassen — baumreife Birnen werden mehlig.',
       'Von Wacholder fernhalten (Wirt des Birnengitterrosts). Spalierformen passen an warme Wände.']],
    ['cherry', 'Kirschbaum', 'tree', 4000, 3500, 4500, 'garlic,chives', 'walnut',
      ['Full sun.',
       'Even moisture as fruit ripens — drought then rain splits cherries.',
       'Deep, warm, limy soil.',
       'Plant in autumn; sweet cherries usually need a pollinator, sour cherries are self-fertile.',
       'Pick fully colored with the stalk; harvest fast, birds are faster.',
       'Prune right after harvest (summer), not in winter — cherries gum on big cuts. Net against birds.'],
      ['Volle Sonne.',
       'Zur Fruchtreife gleichmäßig feucht — Trockenheit mit anschließendem Regen lässt Kirschen platzen.',
       'Tiefgründiger, warmer, kalkhaltiger Boden.',
       'Im Herbst pflanzen; Süßkirschen brauchen meist einen Befruchter, Sauerkirschen sind selbstfruchtbar.',
       'Voll ausgefärbt mit Stiel pflücken; schnell ernten, die Vögel sind schneller.',
       'Direkt nach der Ernte schneiden (Sommer), nicht im Winter — Kirschen gummieren an großen Wunden. Gegen Vögel einnetzen.']],
    ['plum', 'Zwetschgenbaum', 'tree', 3500, 3000, 4000, 'garlic', 'walnut',
      ['Full sun.',
       'Even moisture during fruit swell.',
       'Deep, moist, nutrient-rich soil.',
       'Plant in autumn; many varieties are self-fertile.',
       'Fully ripe off the tree — with a dusty bloom and soft flesh around the stone.',
       'Thin heavy crops to avoid branch breakage and alternate bearing; summer pruning.'],
      ['Volle Sonne.',
       'Während des Fruchtwachstums gleichmäßig feucht.',
       'Tiefgründiger, frischer, nährstoffreicher Boden.',
       'Im Herbst pflanzen; viele Sorten sind selbstfruchtbar.',
       'Vollreif vom Baum — mit Duftfilm und weichem Fleisch um den Stein.',
       'Vollbehang ausdünnen gegen Astbruch und Alternanz; Sommerschnitt.']],
    ['peach', 'Pfirsichbaum', 'tree', 3000, 2500, 3500, 'garlic,onion', 'walnut',
      ['Full sun, warm and sheltered — a south wall is ideal.',
       'Regular in summer; peaches are thirsty while fruiting.',
       'Warm, well-drained soil.',
       'Plant in spring in cold regions; self-fertile.',
       'Ripe when the flesh yields near the stalk and the aroma is strong.',
       'Prune hard each year (fruit only on last year’s shoots). Spray against leaf curl BEFORE bud break.'],
      ['Volle Sonne, warm und geschützt — eine Südwand ist ideal.',
       'Im Sommer regelmäßig; Pfirsiche sind während der Fruchtbildung durstig.',
       'Warmer, durchlässiger Boden.',
       'In kalten Lagen im Frühjahr pflanzen; selbstfruchtbar.',
       'Reif, wenn das Fleisch am Stielansatz nachgibt und stark duftet.',
       'Jährlich kräftig schneiden (Frucht nur am vorjährigen Holz). VOR dem Austrieb gegen Kräuselkrankheit spritzen.']],
    ['apricot', 'Aprikosenbaum', 'tree', 3000, 2500, 3500, 'garlic', 'walnut',
      ['Full sun, warm; avoid frost pockets.',
       'Moderate; established trees handle drought.',
       'Warm, limy, well-drained soil.',
       'Plant in spring against a warm wall; it flowers very early — late frost is the main enemy.',
       'Fully colored and slightly soft; ripens over 2–3 weeks.',
       'Fleece over the blossom on frost nights. Prune after harvest, sparingly.'],
      ['Volle Sonne, warm; Frostlagen meiden.',
       'Mäßig; etablierte Bäume vertragen Trockenheit.',
       'Warmer, kalkhaltiger, durchlässiger Boden.',
       'Im Frühjahr an eine warme Wand pflanzen; blüht sehr früh — Spätfrost ist der Hauptfeind.',
       'Voll ausgefärbt und leicht weich; reift über 2–3 Wochen.',
       'In Frostnächten Vlies über die Blüte. Nach der Ernte sparsam schneiden.']],
    ['quince', 'Quittenbaum', 'tree', 3500, 3000, 4000, '', 'walnut',
      ['Full sun to light shade.',
       'Young trees regularly; later robust.',
       'Undemanding; avoids heavy lime.',
       'Plant in autumn; self-fertile and very low-maintenance.',
       'Late autumn, when fully yellow and fragrant; always cook — raw quinces are hard and astringent.',
       'Barely needs pruning; rub off the fluff before processing.'],
      ['Volle Sonne bis lichter Schatten.',
       'Junge Bäume regelmäßig; später robust.',
       'Anspruchslos; meidet stark kalkhaltige Böden.',
       'Im Herbst pflanzen; selbstfruchtbar und sehr pflegeleicht.',
       'Spätherbst, wenn voll gelb und duftend; immer kochen — rohe Quitten sind hart und herb.',
       'Braucht kaum Schnitt; vor der Verarbeitung den Flaum abreiben.']],
    ['fig', 'Feigenbaum', 'tree', 2500, 2500, 3000, '', '',
      ['Full sun against a warm, sheltered wall.',
       'Regular in pots; restrained in the ground — drought sweetens the fruit.',
       'Well-drained; restrict the roots for better fruiting.',
       'Plant hardy varieties in spring; in cold regions grow in a large pot.',
       'Ripe when the fruit droops, softens and the skin tears slightly.',
       'Fruits on new and last year’s wood; protect young plants in winter.'],
      ['Volle Sonne an einer warmen, geschützten Wand.',
       'Im Topf regelmäßig; im Boden zurückhaltend — Trockenheit macht die Früchte süßer.',
       'Durchlässig; Wurzelbegrenzung fördert den Fruchtansatz.',
       'Winterharte Sorten im Frühjahr pflanzen; in kalten Lagen im großen Kübel.',
       'Reif, wenn die Frucht hängt, weich wird und die Haut leicht aufreißt.',
       'Trägt am neuen und vorjährigen Holz; junge Pflanzen im Winter schützen.']],
    ['walnut', 'Walnussbaum', 'tree', 8000, 8000, 10000, '', '',
      ['Full sun; needs a LOT of space.',
       'Young trees in drought; later self-sufficient.',
       'Deep, nutrient-rich soil.',
       'Plant in autumn, at least 10 m from buildings and beds.',
       'Collect nuts as they drop in autumn; dry airy for 4–6 weeks.',
       'Its roots and leaves release juglone, which suppresses most plants beneath — plant nothing sensitive under it. Prune only in late summer (it bleeds heavily).'],
      ['Volle Sonne; braucht SEHR viel Platz.',
       'Junge Bäume bei Trockenheit; später versorgt er sich selbst.',
       'Tiefgründiger, nährstoffreicher Boden.',
       'Im Herbst pflanzen, mindestens 10 m von Gebäuden und Beeten entfernt.',
       'Nüsse im Herbst auflesen; 4–6 Wochen luftig trocknen.',
       'Wurzeln und Laub geben Juglon ab, das die meisten Pflanzen darunter hemmt — nichts Empfindliches unterpflanzen. Nur im Spätsommer schneiden (starkes Bluten).']],
    ['hazelnut', 'Haselnuss', 'shrub', 3500, 3000, 3000, '', '',
      ['Sun to half shade.',
       'Only young plants need watering.',
       'Undemanding; any decent soil.',
       'Plant two varieties for wind pollination, 3 m apart.',
       'When the husks brown and nuts drop, gather promptly (squirrels!).',
       'Remove a third of the oldest shoots at the base every few years.'],
      ['Sonne bis Halbschatten.',
       'Nur junge Pflanzen gießen.',
       'Anspruchslos; jeder gute Boden.',
       'Zwei Sorten für die Windbestäubung pflanzen, Abstand 3 m.',
       'Wenn die Hüllen bräunen und Nüsse fallen, zügig sammeln (Eichhörnchen!).',
       'Alle paar Jahre ein Drittel der ältesten Triebe bodennah entfernen.']],

    // ---------- ornamental trees & shrubs ----------
    ['birch', 'Birke', 'tree', 12000, 6000, 6000, '', '',
      ['Full sun.',
       'Thirsty — keeps lawns under it dry.',
       'Undemanding, prefers light acid soil.',
       'Plant young in autumn; birches resent transplanting when older.',
       '',
       'Elegant white bark; prune only in late summer (heavy spring bleeding). Strong pollen producer.'],
      ['Volle Sonne.',
       'Durstig — hält den Rasen darunter trocken.',
       'Anspruchslos, bevorzugt leichte, saure Böden.',
       'Jung im Herbst pflanzen; ältere Birken vertragen kein Verpflanzen.',
       '',
       'Elegante weiße Rinde; nur im Spätsommer schneiden (starkes Bluten im Frühjahr). Starker Pollenspender.']],
    ['maple', 'Ahorn', 'tree', 10000, 7000, 7000, '', '',
      ['Sun to half shade.',
       'Moderate; mulch young trees.',
       'Deep, fresh soil.',
       'Plant in autumn; Japanese maples stay small and suit courtyards.',
       '',
       'Brilliant autumn color. Prune only lightly in late summer.'],
      ['Sonne bis Halbschatten.',
       'Mäßig; junge Bäume mulchen.',
       'Tiefgründiger, frischer Boden.',
       'Im Herbst pflanzen; Fächerahorne bleiben klein und passen in Höfe.',
       '',
       'Leuchtende Herbstfärbung. Nur leicht und im Spätsommer schneiden.']],
    ['oak', 'Eiche', 'tree', 15000, 10000, 10000, '', '',
      ['Full sun.',
       'Deep roots; only young trees need water.',
       'Deep, loamy soil.',
       'Plant in autumn — a tree for generations, allow 10 m clearance.',
       '',
       'Supports hundreds of insect and bird species — the most valuable wildlife tree.'],
      ['Volle Sonne.',
       'Tiefwurzler; nur junge Bäume gießen.',
       'Tiefgründiger, lehmiger Boden.',
       'Im Herbst pflanzen — ein Baum für Generationen, 10 m Abstand einplanen.',
       '',
       'Beherbergt hunderte Insekten- und Vogelarten — der wertvollste Naturschutzbaum.']],
    ['linden', 'Linde', 'tree', 15000, 10000, 10000, '', '',
      ['Sun to half shade.',
       'Moderate; tolerates urban conditions.',
       'Deep, fresh soil.',
       'Plant in autumn; takes pruning well, even as shaped/pleached forms.',
       '',
       'Fragrant summer flowers, prized by bees (linden honey). Aphid honeydew drips on cars beneath.'],
      ['Sonne bis Halbschatten.',
       'Mäßig; verträgt Stadtklima.',
       'Tiefgründiger, frischer Boden.',
       'Im Herbst pflanzen; sehr schnittverträglich, auch als Formgehölz/Dachlinde.',
       '',
       'Duftende Sommerblüte, von Bienen geschätzt (Lindenhonig). Honigtau der Blattläuse tropft auf darunter Geparktes.']],
    ['rowan', 'Eberesche', 'tree', 8000, 4000, 4000, '', '',
      ['Sun to half shade.',
       'Modest; tolerates wind and cold.',
       'Undemanding, even poor soils.',
       'Plant in autumn; a tough pioneer tree for exposed spots.',
       '',
       'Orange berry clusters feed dozens of bird species in autumn.'],
      ['Sonne bis Halbschatten.',
       'Genügsam; verträgt Wind und Kälte.',
       'Anspruchslos, auch magere Böden.',
       'Im Herbst pflanzen; ein robuster Pionierbaum für exponierte Lagen.',
       '',
       'Orange Beerendolden ernähren im Herbst Dutzende Vogelarten.']],
    ['magnolia', 'Magnolie', 'tree', 5000, 4000, 4000, '', '',
      ['Sun, sheltered from east winds (frost on open blossom).',
       'Even moisture; shallow roots, mulch generously.',
       'Humus-rich, slightly acid soil.',
       'Plant in spring; choose the spot for good — magnolias hate moving.',
       '',
       'Spectacular early bloom. Do not dig beneath it; prune as little as possible.'],
      ['Sonne, geschützt vor Ostwind (Frost auf offener Blüte).',
       'Gleichmäßig feucht; Flachwurzler, großzügig mulchen.',
       'Humusreicher, leicht saurer Boden.',
       'Im Frühjahr pflanzen; den Standort endgültig wählen — Magnolien hassen Umpflanzen.',
       '',
       'Spektakuläre Frühjahrsblüte. Nicht darunter graben; so wenig wie möglich schneiden.']],
    ['thuja', 'Thuja', 'shrub', 3000, 800, 600, '', '',
      ['Sun to half shade.',
       'Never let it dry out — brown patches are permanent.',
       'Fresh, nutrient-rich soil.',
       'For hedges plant 600 mm apart in autumn.',
       '',
       'Trim twice a year, never into old brown wood — it does not regrow there. All parts are poisonous.'],
      ['Sonne bis Halbschatten.',
       'Nie austrocknen lassen — braune Stellen bleiben.',
       'Frischer, nährstoffreicher Boden.',
       'Für Hecken im Herbst mit 600 mm Abstand pflanzen.',
       '',
       'Zweimal jährlich schneiden, nie ins alte braune Holz — dort treibt sie nicht nach. Alle Teile sind giftig.']],
    ['boxwood', 'Buchsbaum', 'shrub', 800, 600, 500, 'rose', '',
      ['Sun to shade — extremely tolerant.',
       'Moderate; water evergreens in winter dry spells too.',
       'Limy, humus-rich soil.',
       'Plant in spring; classic low edging at 250 mm spacing.',
       '',
       'Check regularly for box tree moth (webbing, bare patches); trim shapes in early and late summer.'],
      ['Sonne bis Schatten — extrem tolerant.',
       'Mäßig; Immergrüne auch in winterlichen Trockenphasen gießen.',
       'Kalkhaltiger, humusreicher Boden.',
       'Im Frühjahr pflanzen; als niedrige Einfassung mit 250 mm Abstand.',
       '',
       'Regelmäßig auf Buchsbaumzünsler prüfen (Gespinste, kahle Stellen); Formschnitt im Früh- und Spätsommer.']],
    ['rose', 'Rose', 'shrub', 1200, 600, 500, 'lavender,garlic,boxwood', '',
      ['Full sun with moving air — that keeps the leaves healthy.',
       'Deep watering at the base; never over the leaves.',
       'Deep, loamy, nutrient-rich soil; never replant roses where roses grew.',
       'Plant bare-root in autumn, graft point 50 mm below soil level.',
       'Cut flowers in the morning; deadhead repeat bloomers continuously.',
       'Spring prune to outward-facing buds; lavender and garlic nearby deter aphids.'],
      ['Volle Sonne mit Luftbewegung — das hält das Laub gesund.',
       'Durchdringend an der Basis gießen; nie über die Blätter.',
       'Tiefgründiger, lehmiger, nährstoffreicher Boden; nie Rosen auf alten Rosenstandort.',
       'Wurzelnackt im Herbst pflanzen, Veredelungsstelle 50 mm unter der Erde.',
       'Blüten morgens schneiden; öfterblühende laufend ausputzen.',
       'Frühjahrsschnitt auf nach außen zeigende Knospen; Lavendel und Knoblauch daneben vertreiben Blattläuse.']],
    ['hydrangea', 'Hortensie', 'shrub', 1500, 1200, 1200, '', '',
      ['Half shade; morning sun, afternoon shade.',
       'Very thirsty (the name says it) — never let it dry out.',
       'Humus-rich, slightly acid soil; blue varieties need pH < 5.5 and alum.',
       'Plant in spring, 1.2 m apart.',
       '',
       'Farmer’s hydrangeas flower on old wood — only deadhead in spring; panicle hydrangeas take hard pruning.'],
      ['Halbschatten; Morgensonne, Nachmittagsschatten.',
       'Sehr durstig (der Name sagt es) — nie austrocknen lassen.',
       'Humusreicher, leicht saurer Boden; blaue Sorten brauchen pH < 5,5 und Alaun.',
       'Im Frühjahr pflanzen, Abstand 1,2 m.',
       '',
       'Bauernhortensien blühen am alten Holz — im Frühjahr nur Verblühtes entfernen; Rispenhortensien vertragen starken Rückschnitt.']],
    ['sunflower', 'Sonnenblume', 'flower', 2500, 500, 500, 'cucumber,corn', 'potato,beans',
      ['Full sun — the head follows it.',
       'Generous; big leaves, big thirst.',
       'Rich, deep soil.',
       'Sow in place after the last frost, 500 mm apart; stake tall varieties.',
       'For seeds, let the head ripen until the back turns yellow-brown.',
       'A bird buffet in autumn — leave the seed heads standing.'],
      ['Volle Sonne — der Kopf folgt ihr.',
       'Großzügig gießen; große Blätter, großer Durst.',
       'Nährstoffreicher, tiefgründiger Boden.',
       'Nach den letzten Frösten an Ort und Stelle säen, Abstand 500 mm; hohe Sorten stäben.',
       'Für Kerne den Kopf ausreifen lassen, bis die Rückseite gelbbraun ist.',
       'Ein Vogelbuffet im Herbst — die Samenstände stehen lassen.']]
  ];

  var CARE_KEYS = ['sun', 'water', 'soil', 'planting', 'harvest', 'notes'];
  var HABITS = ['leafy', 'bushy', 'vining', 'climbing', 'root', 'herb', 'flower', 'shrub', 'tree', 'grass'];
  var LS_KEY = 'diyw_plants';

  function num(v, d) { v = Number(v); return isFinite(v) && v > 0 ? v : d; }

  function strList(a) {
    if (typeof a === 'string') a = a.split(',');
    return (Array.isArray(a) ? a : []).map(function (s) { return String(s).toLowerCase().trim(); }).filter(Boolean);
  }

  // Normalize a (possibly user-edited) entry into the canonical shape.
  function normalize(e) {
    e = e || {};
    function careObj(c) {
      var o = {};
      CARE_KEYS.forEach(function (k) { o[k] = (c && c[k]) ? String(c[k]) : ''; });
      return o;
    }
    var care = e.care || {};
    return {
      species: String(e.species || '').toLowerCase().trim(),
      de: String(e.de || '').trim(),
      habit: HABITS.indexOf(e.habit) >= 0 ? e.habit : 'bushy',
      height: num(e.height, 300), dia: num(e.dia, 250), spacing: num(e.spacing, 250),
      companions: strList(e.companions),
      avoid: strList(e.avoid),
      care: { en: careObj(care.en), de: careObj(care.de) }
    };
  }

  function defaults() {
    return DB.map(function (r) {
      function care(arr) {
        var c = {};
        CARE_KEYS.forEach(function (k, i) { c[k] = arr[i] || ''; });
        return c;
      }
      return {
        species: r[0], de: r[1], habit: r[2],
        height: r[3], dia: r[4], spacing: r[5],
        companions: r[6] ? r[6].split(',') : [],
        avoid: r[7] ? r[7].split(',') : [],
        care: { en: care(r[8]), de: care(r[9]) }
      };
    });
  }

  // Current catalog: built-in defaults, or the user's edited set from localStorage.
  var current, byKey;
  function rebuildIndex() {
    byKey = {};
    current.forEach(function (e) { if (e.species) byKey[e.species] = e; });
  }
  function load() {
    try {
      var s = JSON.parse(localStorage.getItem(LS_KEY) || 'null');
      if (Array.isArray(s) && s.length) return s.map(normalize).filter(function (e) { return e.species; });
    } catch (err) {}
    return defaults();
  }
  current = load();
  rebuildIndex();

  function save(entries) {
    current = (entries || []).map(normalize).filter(function (e) { return e.species; });
    if (!current.length) current = defaults();   // empty save = back to defaults (like the wood inventory)
    rebuildIndex();
    localStorage.setItem(LS_KEY, JSON.stringify(current));
    return current;
  }

  function reset() {
    try { localStorage.removeItem(LS_KEY); } catch (err) {}
    current = defaults();
    rebuildIndex();
    return current;
  }

  function list() { return current; }

  // Lookup with light normalization: lowercase, trim, singular/plural fallback.
  function get(species) {
    var s = String(species || '').toLowerCase().trim();
    if (byKey[s]) return byKey[s];
    if (byKey[s + 's']) return byKey[s + 's'];
    if (s.slice(-1) === 's' && byKey[s.slice(0, -1)]) return byKey[s.slice(0, -1)];
    return null;
  }

  function careFor(species, lang) {
    var e = get(species);
    return e ? e.care[lang === 'de' ? 'de' : 'en'] : null;
  }

  function labelFor(species, lang) {
    var e = get(species);
    return (e && lang === 'de') ? e.de : null;
  }

  // Compact catalog block for the garden-mode LLM prompts (no care texts — too big).
  function promptBlock() {
    var lines = [
      'PLANT CATALOG — built-in species with reliable bilingual data (vegetables, herbs, berries, fruit and',
      'ornamental trees). STRONGLY PREFER these species. Use the exact English key in "species"; write the',
      'plant "name" in the user\'s language (the German name is listed below).',
      'For catalog species you may OMIT habit, matureHeight, matureDiameter, spacing, companions and avoid',
      '(catalog defaults apply) and leave every "care" field as "" — the tool fills them from the catalog in',
      'the user\'s language. Write care text ONLY for species not listed here, or to add special instructions.',
      'format: species | German | habit | height | Ø | spacing (mm) | companions | avoid'
    ];
    current.forEach(function (e) {
      lines.push('- ' + e.species + ' | ' + (e.de || '—') + ' | ' + e.habit + ' | ' + e.height + ' | ' + e.dia + ' | ' + e.spacing +
        ' | ' + (e.companions.join(',') || '—') + ' | ' + (e.avoid.join(',') || '—'));
    });
    lines.push('Invent a custom species (with FULL care data in the user\'s language) only when the user asks for something not listed.');
    return lines.join('\n');
  }

  window.PlantDB = {
    CARE_KEYS: CARE_KEYS,
    HABITS: HABITS,
    list: list,
    defaults: defaults,
    save: save,
    reset: reset,
    get: get,
    careFor: careFor,
    labelFor: labelFor,
    promptBlock: promptBlock
  };
})();
